name = "webshare-final"
main = "final-worker.js"
compatibility_date = "2024-01-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"